// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceType } from "./ResourceType";

export type ResourceRef = { providerId: string, resourceId: string, revision: string, resourceType: ResourceType, };
