// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceBindingMode } from "./ResourceBindingMode";
import type { ResourceRef } from "./ResourceRef";

export type ResourceBindParams = { connectionId: string, workspaceBindingId: string, resource: ResourceRef, mode: ResourceBindingMode, };
