// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Replace the exact Provider resource bindings of an existing thread authority.
 */
export type ThreadExecutionContextUpdateParams = { threadId: string, workspaceBindingId: string, resourceBindingIds: Array<string>, executionBindingId?: string | null, expectedRevision: bigint, };
