// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact Provider resource binding revision attached to one thread.
 */
export type ThreadExecutionContextBindingRef = { bindingId: string, revision: bigint, };
