// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paginated request for roots already registered by app-server configuration.
 */
export type WorkspaceListParams = { cursor?: string | null, limit?: number | null, };
