// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceAvailability } from "./WorkspaceAvailability";

/**
 * Path-free projection of one server-registered workspace root.
 */
export type WorkspaceSummary = { workspaceKey: string, displayName: string, nodeId: string, environmentId: string, availability: WorkspaceAvailability, };
