// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceAccessMode } from "./WorkspaceAccessMode";
import type { WorkspaceSummary } from "./WorkspaceSummary";

/**
 * Path-free workspace roots visible to the current connection session.
 */
export type WorkspaceListResponse = { data: Array<WorkspaceSummary>, nextCursor: string | null, accessMode: WorkspaceAccessMode, };
