// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceScope } from "./WorkspaceScope";

/**
 * Request to bind one session workspace key to a domain scope.
 */
export type WorkspaceBindParams = { workspaceKey: string, scope: WorkspaceScope, scopeId: string, };
