[package]
edition.workspace = true
license.workspace = true
name = "crewon-plugin"
version.workspace = true

[lib]
doctest = false
name = "crewon_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
crewon-config = { workspace = true }
crewon-utils-absolute-path = { workspace = true }
crewon-utils-plugins = { workspace = true }
thiserror = { workspace = true }
