// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderProbeStatus } from "./ModelProviderProbeStatus";

export type ModelProviderProbeResponse = {
/**
 * Provider that was probed, so a client can tell which entry answered.
 */
providerId: string,
/**
 * Endpoint the probe requested, for surfacing a wrong base URL.
 */
endpoint: string, status: ModelProviderProbeStatus,
/**
 * HTTP status returned by the provider, when it answered at all.
 */
httpStatus: number | null,
/**
 * Models the provider advertised, when the catalog parsed.
 */
modelCount: number | null,
/**
 * Whether a credential was attached, so "works without auth" is visible.
 */
authenticated: boolean,
/**
 * Failure detail from the provider or transport.
 */
message: string | null, latencyMs: bigint, };
