[package]
edition.workspace = true
license.workspace = true
name = "crewon-core-skills"
version.workspace = true

[lib]
doctest = false
name = "crewon_core_skills"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
crewon-analytics = { workspace = true }
crewon-app-server-protocol = { workspace = true }
crewon-config = { workspace = true }
crewon-context-fragments = { workspace = true }
crewon-exec-server = { workspace = true }
crewon-login = { workspace = true }
crewon-model-provider = { workspace = true }
crewon-otel = { workspace = true }
crewon-protocol = { workspace = true }
crewon-skills = { workspace = true }
crewon-utils-absolute-path = { workspace = true }
crewon-utils-output-truncation = { workspace = true }
crewon-utils-plugins = { workspace = true }
dirs = { workspace = true }
dunce = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt"] }
toml = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
