// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AgentPlatformResourceStatus } from "./AgentPlatformResourceStatus";
import type { AgentPlatformResourceType } from "./AgentPlatformResourceType";

export type AgentPlatformResourceEvent = { type: AgentPlatformResourceType, status: AgentPlatformResourceStatus, name: string, inputSummary: JsonValue, outputSummary: JsonValue, error: string | null, };
