// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentPlatformAgentInfoResponse = { id: bigint, uid: string | null, name: string, description: string | null, maxConcurrency: number, activeConnections: number, };
