// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AgentPlatformResourceEvent } from "./AgentPlatformResourceEvent";
import type { AgentPlatformTokenUsage } from "./AgentPlatformTokenUsage";

export type AgentPlatformChatResponse = { agentId: string, message: string, thoughts: Array<JsonValue>, skillsUsed: Array<JsonValue>, resourceEvents: Array<AgentPlatformResourceEvent>, tokens: AgentPlatformTokenUsage, durationMs: bigint, };
