// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AgentPlatformWorkflowExecuteResponse = { workflowId: bigint, executionId: bigint, status: string, outputs: JsonValue, startedAt: string | null, finishedAt: string | null, durationSeconds: number | null, executedNodes: Array<JsonValue>, nodeResults: JsonValue, error: string | null, activeConnections: number, };
