// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPlatformResourceEvent } from "./AgentPlatformResourceEvent";

export type AgentPlatformResourceEventNotification = { runId: string, threadId: string, agentId: string, event: AgentPlatformResourceEvent, };
