// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";

export type ApprovalRef = { approvalId: string, actionDigest: string, status: ApprovalStatus, expiresAt: bigint | null, };
