// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKind } from "./ArtifactKind";
import type { RetentionClass } from "./RetentionClass";

export type ArtifactRef = { artifactId: string, taskId: string, kind: ArtifactKind, revision: bigint, retention: RetentionClass, createdAt: bigint, };
