// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutomationReadParams = { cwd: string, filePath?: string | null, threadId?: string | null, title?: string | null, };
