// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AutomationCreateParams = { cwd: string, title: string, threadId?: string | null, targetOffice?: JsonValue | null, executionAgent?: JsonValue | null, prompt?: string | null, enabled?: boolean | null, status?: string | null, };
