// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AutomationRunRecord = { runId: string, automationTitle: string, threadId: string | null, status: string, startedAt: bigint, completedAt: bigint | null, note: string | null, config: JsonValue, };
