// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialScope } from "./CredentialScope";
import type { CredentialStatus } from "./CredentialStatus";

export type CredentialRef = { credentialId: string, providerId: string, scope: CredentialScope, status: CredentialStatus, expiresAt: bigint | null, revision: bigint, };
