// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ToolConfigKind } from "./ToolConfigKind";

export type CrewonToolConfigRecord = { filePath: string, savedAt: string, kind: ToolConfigKind, config: JsonValue, };
