// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bounded local role in an Experts definition.
 */
export type ExpertRole = { name: string, role: string, agentType: string, instructions: string | null, };
