// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpertRole } from "./ExpertRole";

/**
 * Path-free Experts definition owned by one subject and Conversation workspace.
 */
export type ExpertTeamConfig = { expertsId: string, title: string, goal: string, leader: ExpertRole, experts: Array<ExpertRole>, recordRevision: string, workspaceKey: string, ownerSubject: string, tenantId: string | null, spaceId: string | null, };
