// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpertRole } from "./ExpertRole";

export type ExpertTeamCreateParams = { workspaceKey: string, title: string, goal: string, leader: ExpertRole, experts: Array<ExpertRole>, };
