// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpertTeamConfig } from "./ExpertTeamConfig";

/**
 * Server-owned Experts record projection. The file path is never accepted in create/read params.
 */
export type ExpertTeamRecord = { filePath: string, config: ExpertTeamConfig, };
