// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnowledgeSource = { name: string, glyph: string, accent: string, status: string, path: string, isDirectory: boolean, meta: string, };
