// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeEntry } from "./KnowledgeEntry";
import type { KnowledgeSource } from "./KnowledgeSource";

export type KnowledgeData = { memories: Array<KnowledgeEntry>, sources: Array<KnowledgeSource>, };
