// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnowledgeMemoryWriteParams = { cwd: string, title?: string | null, threadId?: string | null, note?: string | null, };
