// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfigWriteResult } from "./McpServerConfigWriteResult";

export type McpServerConfigSaveResponse = { write: McpServerConfigWriteResult, reloadError: string | null, };
