// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a provider reachability check.
 *
 * The model catalog falls back to a bundled list when a provider cannot be
 * reached, so `model/list` succeeding says nothing about whether the
 * configured provider actually works. These variants let a client tell a
 * wrong key apart from a wrong address instead of reporting one generic
 * failure.
 */
export type ModelProviderProbeStatus = "ok" | "unauthorized" | "httpError" | "unreachable" | "invalidResponse";
