// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { Turn } from "./Turn";

export type OfficeRunSyncParams = { cwd: string, config: JsonValue, runId?: string | null, turn: Turn, locale?: string | null, };
