// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfficeAutomationBindingPolicy } from "./OfficeAutomationBindingPolicy";

export type OfficeAutomationBinding = { bindingVersion: number, bindingId: string, automationFilePath: string, automationIdentity: string, automationTitle: string, policy: OfficeAutomationBindingPolicy, createdAt: bigint, updatedAt: bigint, };
