// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfficeMemoryEvidenceRef } from "./OfficeMemoryEvidenceRef";

export type OfficeMemoryRecord = { id: string, officeKey: string, scope: string, member: string | null, agentId: string | null, kind: string, content: string, confidence: string, importance: string, status: string, evidenceRefs: Array<OfficeMemoryEvidenceRef>, keywords: Array<string>, createdAt: string, updatedAt: string, lastUsedAt: string | null, usageCount: number, };
