// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { OfficeApprovalDecision } from "./OfficeApprovalDecision";

export type OfficeApprovalDecideParams = { cwd: string, config: JsonValue, approvalId: string, decision: OfficeApprovalDecision, message?: JsonValue | null, };
