// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type OfficeRunUpdatedNotification = { cwd: string, filePath: string, config: JsonValue, reason: string, sourceThreadId: string | null, sourceTurnId: string | null, };
