// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfficeMessageProcessingPhase } from "./OfficeMessageProcessingPhase";
import type { Turn } from "./Turn";

export type OfficeMessageDelivery = { "type": "processing", phase: OfficeMessageProcessingPhase, retryAfterMs: number, } | { "type": "runStarted", runId: string, threadId: string, turn: Turn, } | { "type": "interactionStarted", interactionId: string, threadId: string, turn: Turn, } | { "type": "steered", runId: string, threadId: string, turnId: string, } | { "type": "queued", afterRunId: string, position: number, } | { "type": "answered", interactionId: string, threadId: string, turnId: string, } | { "type": "failed", code: string, message: string, retryable: boolean, };
