// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OfficeCreateParams = { cwd: string, title: string, subtitle?: string | null, threadId?: string | null, goal?: string | null, };
