// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { OfficeMessageDelivery } from "./OfficeMessageDelivery";

export type OfficeMessageSubmitResponse = { filePath: string, config: JsonValue, receiptId: string, clientUserMessageId: string, replayed: boolean, delivery: OfficeMessageDelivery, };
