// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { OfficeMessageMention } from "./OfficeMessageMention";

export type OfficeMessageSubmitParams = { cwd: string, config: JsonValue, text: string, clientUserMessageId: string, locale?: string | null, threadId?: string | null, mentions?: Array<OfficeMessageMention> | null, };
