// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type OfficeRunParams = { cwd: string, config: JsonValue, message: JsonValue, text: string, locale?: string | null, threadId?: string | null, clientUserMessageId?: string | null, };
