// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OfficeMemberContextPreviewResponse = { runId: string, member: string, agentId: string, threadId: string, contextPolicy: string, memoryScope: string, agentProfile: string, sharedContext: string, memoryContext: string, };
