// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type OfficeMemberContextPreviewParams = { cwd: string, config: JsonValue, runId: string, task?: string | null, member?: string | null, agentId?: string | null, locale?: string | null, };
