// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfficeAutomationBindingApprovalMode } from "./OfficeAutomationBindingApprovalMode";
import type { OfficeAutomationBindingDispatchMode } from "./OfficeAutomationBindingDispatchMode";
import type { OfficeAutomationBindingRiskLevel } from "./OfficeAutomationBindingRiskLevel";
import type { OfficeAutomationBindingStatus } from "./OfficeAutomationBindingStatus";

export type OfficeAutomationBindingPolicy = { dispatchMode: OfficeAutomationBindingDispatchMode, riskLevel: OfficeAutomationBindingRiskLevel, approvalMode: OfficeAutomationBindingApprovalMode, status: OfficeAutomationBindingStatus, };
