// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformErrorCode } from "./PlatformErrorCode";

export type PlatformErrorRef = { code: PlatformErrorCode, retryable: boolean, traceId: string, };
