// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalRef } from "./ApprovalRef";
import type { ArtifactRef } from "./ArtifactRef";
import type { AutomationRef } from "./AutomationRef";
import type { CredentialRef } from "./CredentialRef";
import type { PlatformErrorRef } from "./PlatformErrorRef";
import type { ProviderRef } from "./ProviderRef";
import type { RequestIdentityRef } from "./RequestIdentityRef";
import type { ResourceBindingRef } from "./ResourceBindingRef";
import type { TaskEventRef } from "./TaskEventRef";
import type { TaskRef } from "./TaskRef";
import type { TeamRef } from "./TeamRef";
import type { WorkspaceRef } from "./WorkspaceRef";

export type PlatformContract = { schemaVersion: string, identity: RequestIdentityRef, workspace: WorkspaceRef, credential: CredentialRef, provider: ProviderRef, resourceBinding: ResourceBindingRef, task: TaskRef, event: TaskEventRef, approval: ApprovalRef, artifact: ArtifactRef, team: TeamRef, automation: AutomationRef, error: PlatformErrorRef, };
