// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderRunInput } from "./ProviderRunInput";
import type { ResourceRef } from "./ResourceRef";

export type ProviderStartCommand = { commandId: string, idempotencyKey: string, requestDigest: string, resource: ResourceRef, input: ProviderRunInput, };
