// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCapabilityKind } from "./ProviderCapabilityKind";
import type { ProviderConnectionStatus } from "./ProviderConnectionStatus";
import type { ProviderKind } from "./ProviderKind";

export type ProviderRef = { providerId: string, kind: ProviderKind, status: ProviderConnectionStatus, capabilities: Array<ProviderCapabilityKind>, };
