// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformErrorCode } from "./PlatformErrorCode";
import type { RequiredNullableString } from "./RequiredNullableString";

export type ProviderContractError = { code: PlatformErrorCode, retryable: boolean, providerRunId: RequiredNullableString, traceId: string, };
