// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCredentialAuthorization } from "./ProviderCredentialAuthorization";
import type { ProviderDelegationAuthorization } from "./ProviderDelegationAuthorization";

export type ProviderAuthorization = { serviceAudience: string, tenantId: string, spaceId: string, taskId: string, subject: string, scopes: Array<string>, purpose: string, credential: ProviderCredentialAuthorization, delegation: ProviderDelegationAuthorization, };
