// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderApprovalRequest } from "./ProviderApprovalRequest";

export type ProviderApprovalRequiredEvent = { eventId: string, providerRunId: string, attemptId: string, sequence: bigint, cursor: string, createdAt: bigint, approval: ProviderApprovalRequest, };
