// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderApprovalRequiredEvent } from "./ProviderApprovalRequiredEvent";
import type { ProviderCancelledEvent } from "./ProviderCancelledEvent";
import type { ProviderCompletedEvent } from "./ProviderCompletedEvent";
import type { ProviderFailedEvent } from "./ProviderFailedEvent";
import type { ProviderProgressEvent } from "./ProviderProgressEvent";
import type { ProviderRunStartedEvent } from "./ProviderRunStartedEvent";
import type { ProviderToolResultAcceptedEvent } from "./ProviderToolResultAcceptedEvent";
import type { ProviderToolResultRequiredEvent } from "./ProviderToolResultRequiredEvent";

export type ProviderRunEvent = { "type": "runStarted" } & ProviderRunStartedEvent | { "type": "progress" } & ProviderProgressEvent | { "type": "approvalRequired" } & ProviderApprovalRequiredEvent | { "type": "toolResultRequired" } & ProviderToolResultRequiredEvent | { "type": "toolResultAccepted" } & ProviderToolResultAcceptedEvent | { "type": "completed" } & ProviderCompletedEvent | { "type": "failed" } & ProviderFailedEvent | { "type": "cancelled" } & ProviderCancelledEvent;
