// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCancelCommand } from "./ProviderCancelCommand";
import type { ProviderDecideApprovalCommand } from "./ProviderDecideApprovalCommand";
import type { ProviderListEventsCommand } from "./ProviderListEventsCommand";
import type { ProviderReadCommand } from "./ProviderReadCommand";
import type { ProviderStartCommand } from "./ProviderStartCommand";
import type { ProviderSubmitToolResultCommand } from "./ProviderSubmitToolResultCommand";

export type ProviderCommand = { "type": "start" } & ProviderStartCommand | { "type": "read" } & ProviderReadCommand | { "type": "listEvents" } & ProviderListEventsCommand | { "type": "cancel" } & ProviderCancelCommand | { "type": "decideApproval" } & ProviderDecideApprovalCommand | { "type": "submitToolResult" } & ProviderSubmitToolResultCommand;
