// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactRef } from "./ArtifactRef";

export type ProviderSubmitToolResultCommand = { commandId: string, providerRunId: string, toolCallId: string, intentDigest: string, resultDigest: string, artifact: ArtifactRef, idempotencyKey: string, };
