// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequiredNullableString } from "./RequiredNullableString";

export type ProviderListEventsCommand = { commandId: string, providerRunId: string, afterCursor: RequiredNullableString, limit: number, };
