// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderContractError } from "./ProviderContractError";

export type ProviderFailedEvent = { eventId: string, providerRunId: string, attemptId: string, sequence: bigint, cursor: string, createdAt: bigint, error: ProviderContractError, };
