// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderApprovalDecision } from "./ProviderApprovalDecision";

export type ProviderDecideApprovalCommand = { commandId: string, providerRunId: string, approvalId: string, decision: ProviderApprovalDecision, actionDigest: string, idempotencyKey: string, };
