// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAuthorization } from "./ProviderAuthorization";
import type { ProviderCommand } from "./ProviderCommand";
import type { ProviderContractDescriptor } from "./ProviderContractDescriptor";
import type { ProviderContractError } from "./ProviderContractError";
import type { ProviderRunEvent } from "./ProviderRunEvent";

export type ProviderContract = { schemaVersion: string, provider: ProviderContractDescriptor, authorization: ProviderAuthorization, commands: Array<ProviderCommand>, events: Array<ProviderRunEvent>, error: ProviderContractError, };
