// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestIdentityClientCapabilitiesRef } from "./RequestIdentityClientCapabilitiesRef";

/**
 * Client metadata declared during initialize.
 *
 * This metadata is intentionally separate from the server-derived identity.
 */
export type RequestIdentityClientRef = { name: string, version: string, capabilities: RequestIdentityClientCapabilitiesRef, };
