// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client capabilities declared during initialize.
 *
 * These fields are negotiation metadata and must not be used as authority.
 */
export type RequestIdentityClientCapabilitiesRef = { experimentalApi: boolean, requestAttestation: boolean, };
