// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestIdentityRef = { actorId: string, tenantId: string | null, spaceId: string | null, sessionId: string, traceId: string, };
