// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trusted transport category that established the app-server connection.
 */
export type RequestIdentityTransport = "stdio" | "inProcess" | "webSocket" | "remoteControl";
