// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionLocation } from "./ExecutionLocation";
import type { ResourceBindingMode } from "./ResourceBindingMode";
import type { ResourceType } from "./ResourceType";

export type ResourceBindingCapability = { resourceType: ResourceType, mode: ResourceBindingMode, executionLocation: ExecutionLocation, };
