// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalActionPolicy } from "./ExternalActionPolicy";
import type { LocalWritePolicy } from "./LocalWritePolicy";
import type { SceneDeliverable } from "./SceneDeliverable";
import type { SceneId } from "./SceneId";
import type { SceneInteractionMode } from "./SceneInteractionMode";

export type SceneTaskContract = { scene: SceneId, mode: SceneInteractionMode, deliverable: SceneDeliverable, localWritePolicy: LocalWritePolicy, externalActionPolicy: ExternalActionPolicy, };
