// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecommendedPermission } from "./RecommendedPermission";
import type { SceneContextSlotDescriptor } from "./SceneContextSlotDescriptor";
import type { SceneDeliverable } from "./SceneDeliverable";
import type { SceneId } from "./SceneId";
import type { SceneInteractionMode } from "./SceneInteractionMode";
import type { SceneModeDescriptor } from "./SceneModeDescriptor";

export type SceneDescriptor = { sceneId: SceneId, labelKey: string, subtitleKey: string, placeholderKey: string, presetVersion: number, instructionVersion: number, defaultMode: SceneInteractionMode, defaultDeliverable: SceneDeliverable, recommendedPermission: RecommendedPermission, contextSlots: Array<SceneContextSlotDescriptor>, modeSpecs: Array<SceneModeDescriptor>, };
