// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneContextKind = "workspace" | "repository" | "branch" | "file" | "document" | "thread" | "issue" | "pull-request" | "calendar" | "contact" | "date-range" | "figma-node" | "knowledge" | "image" | "web-page" | "log" | "brief" | "brand" | "canvas-spec";
