// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneDeliverable = "conversation" | "document" | "table" | "action-list" | "message-draft" | "knowledge-entry" | "implementation-plan" | "code-change" | "code-review" | "design-directions" | "design-artifact" | "design-review" | "handoff-spec";
