// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneExecutionTargetSelection = { "kind": "crewon" } | { "kind": "agent", id: string, } | { "kind": "team", id: string, };
