// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneDeliverable } from "./SceneDeliverable";
import type { SceneInteractionMode } from "./SceneInteractionMode";
import type { SceneTaskContract } from "./SceneTaskContract";

export type SceneModeDescriptor = { mode: SceneInteractionMode, defaultContract: SceneTaskContract, allowedDeliverables: Array<SceneDeliverable>, completionCheckIds: Array<string>, };
