// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskEventType } from "./TaskEventType";

export type TaskEventRef = { eventId: string, taskId: string, attemptId: string | null, workerSequence: bigint | null, streamOffset: bigint, eventType: TaskEventType, createdAt: bigint, };
