// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAuthorityKind } from "./TaskAuthorityKind";
import type { TaskStatus } from "./TaskStatus";
import type { TaskStrategyKind } from "./TaskStrategyKind";

export type TaskRef = { taskId: string, authority: TaskAuthorityKind, strategy: TaskStrategyKind, status: TaskStatus, revision: bigint, streamOffset: bigint, };
