// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type ThreadRollbackResponse = {
/**
 * The updated thread after applying the rollback, with `turns` populated.
 *
 * The ThreadItems stored in each Turn are lossy for some interaction kinds.
 * Agent command executions are retained (with truncated output); user-shell
 * bang commands are still omitted. This matches `thread/resume`.
 */
thread: Thread, };
