// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneExecutionStrategy } from "./SceneExecutionStrategy";
import type { SceneExecutionTargetKind } from "./SceneExecutionTargetKind";
import type { SceneTaskContract } from "./SceneTaskContract";

export type ThreadSceneRuntime = { version: number, presetVersion: number, instructionVersion: number, contract: SceneTaskContract, executionTargetKind: SceneExecutionTargetKind, executionTargetToken: string, executionStrategy: SceneExecutionStrategy, };
