// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneDeliverable } from "./SceneDeliverable";
import type { SceneExecutionTargetSelection } from "./SceneExecutionTargetSelection";
import type { SceneId } from "./SceneId";
import type { SceneInteractionMode } from "./SceneInteractionMode";

export type ThreadSceneSelectionParams = { sceneId: SceneId, mode?: SceneInteractionMode | null, deliverable?: SceneDeliverable | null, executionTarget?: SceneExecutionTargetSelection | null, };
