// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-owned Provider resource selection used when creating a new thread authority.
 */
export type ThreadExecutionContextCreateParams = { workspaceKey: string, };
