// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeDefinition } from "./WorkflowNodeDefinition";

export type WorkflowCreateParams = { cwd: string, name: string, description: string, lead: string, nodes: Array<WorkflowNodeDefinition>, };
