// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current availability of a root already registered in this connection session.
 */
export type WorkspaceAvailability = "available" | "missing" | "unreadable";
