// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeExecution } from "./WorkflowNodeExecution";

export type WorkflowRunResponse = { executionId: string, workflowId: string, status: string, output: string, executedNodes: Array<WorkflowNodeExecution>, error: string | null, };
