// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowGateDecision } from "./WorkflowGateDecision";

export type WorkflowGateResolveParams = { cwd: string, workflowId: string, executionId: string, nodeId: string, decision: WorkflowGateDecision, comment?: string | null, };
