// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceBindingRef } from "./ResourceBindingRef";
import type { ResourceBindingStatus } from "./ResourceBindingStatus";
import type { WorkspaceScope } from "./WorkspaceScope";

export type ResourceBindingProjection = { connectionId: string, binding: ResourceBindingRef, workspaceScope: WorkspaceScope, workspaceScopeId: string, status: ResourceBindingStatus, revision: bigint, updatedAt: bigint, };
