// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceRef } from "./ResourceRef";

export type ResourceListResponse = { data: Array<ResourceRef>, nextCursor: string | null, providerEtag: string, };
