// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadExecutionContextBindingRef } from "./ThreadExecutionContextBindingRef";
import type { WorkspaceRef } from "./WorkspaceRef";

/**
 * Path-free, secret-free projection of a thread's durable execution authority.
 */
export type ThreadExecutionContext = { threadId: string, workspace: WorkspaceRef, resourceBindings: Array<ThreadExecutionContextBindingRef>, executionBinding: ThreadExecutionContextBindingRef | null, revision: bigint, createdAt: bigint, updatedAt: bigint, };
