// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceRef } from "./WorkspaceRef";

/**
 * Server-derived scope binding for a registered workspace root.
 */
export type WorkspaceBindResponse = { workspace: WorkspaceRef, };
