use crate::bespoke_event_handling::apply_bespoke_event_handling;
use crate::bespoke_event_handling::maybe_emit_hook_prompt_item_completed;
use crate::command_exec::CommandExecManager;
use crate::command_exec::StartCommandExecParams;
use crate::config_manager::ConfigManager;
use crate::error_code::INPUT_TOO_LARGE_ERROR_CODE;
use crate::error_code::invalid_params;
use crate::models::supported_models;
use crate::outgoing_message::ConnectionId;
use crate::outgoing_message::ConnectionRequestId;
use crate::outgoing_message::OutgoingMessageSender;
use crate::outgoing_message::RequestContext;
use crate::outgoing_message::ThreadScopedOutgoingMessageSender;
use crate::skills_watcher::SkillsWatcher;
use crate::thread_status::ThreadWatchManager;
use crate::thread_status::resolve_thread_status;
use chrono::Duration as ChronoDuration;
use crewon_analytics::AnalyticsEventsClient;
use crewon_analytics::AnalyticsJsonRpcError;
use crewon_analytics::InputError;
use crewon_analytics::TurnSteerRequestError;
use crewon_app_server_protocol::Account;
use crewon_app_server_protocol::AccountLoginCompletedNotification;
use crewon_app_server_protocol::AccountTokenUsageDailyBucket;
use crewon_app_server_protocol::AccountTokenUsageSummary;
use crewon_app_server_protocol::AccountUpdatedNotification;
use crewon_app_server_protocol::AddCreditsNudgeCreditType;
use crewon_app_server_protocol::AddCreditsNudgeEmailStatus;
use crewon_app_server_protocol::AdditionalContextEntry;
use crewon_app_server_protocol::AdditionalContextKind;
use crewon_app_server_protocol::AppInfo;
use crewon_app_server_protocol::AppListUpdatedNotification;
use crewon_app_server_protocol::AppSummary;
use crewon_app_server_protocol::AppTemplateSummary;
use crewon_app_server_protocol::AppTemplateUnavailableReason;
use crewon_app_server_protocol::AppsListParams;
use crewon_app_server_protocol::AppsListResponse;
use crewon_app_server_protocol::AskForApproval;
use crewon_app_server_protocol::AuthMode;
use crewon_app_server_protocol::CancelLoginAccountParams;
use crewon_app_server_protocol::CancelLoginAccountResponse;
use crewon_app_server_protocol::CancelLoginAccountStatus;
use crewon_app_server_protocol::ClientInfo;
use crewon_app_server_protocol::ClientRequest;
use crewon_app_server_protocol::ClientResponsePayload;
use crewon_app_server_protocol::CodexErrorInfo;
use crewon_app_server_protocol::CollaborationModeListParams;
use crewon_app_server_protocol::CollaborationModeListResponse;
use crewon_app_server_protocol::CommandExecParams;
use crewon_app_server_protocol::CommandExecResizeParams;
use crewon_app_server_protocol::CommandExecTerminateParams;
use crewon_app_server_protocol::CommandExecWriteParams;
use crewon_app_server_protocol::ConfigBatchWriteParams;
use crewon_app_server_protocol::ConfigReadParams;
use crewon_app_server_protocol::ConfigWarningNotification;
use crewon_app_server_protocol::ConfigWriteResponse;
use crewon_app_server_protocol::ConversationGitInfo;
use crewon_app_server_protocol::ConversationSummary;
use crewon_app_server_protocol::DynamicToolSpec as ApiDynamicToolSpec;
use crewon_app_server_protocol::EnvironmentAddParams;
use crewon_app_server_protocol::EnvironmentAddResponse;
use crewon_app_server_protocol::ExperimentalFeature as ApiExperimentalFeature;
use crewon_app_server_protocol::ExperimentalFeatureListParams;
use crewon_app_server_protocol::ExperimentalFeatureListResponse;
use crewon_app_server_protocol::ExperimentalFeatureStage as ApiExperimentalFeatureStage;
use crewon_app_server_protocol::FeedbackUploadParams;
use crewon_app_server_protocol::FeedbackUploadResponse;
use crewon_app_server_protocol::GetAccountParams;
use crewon_app_server_protocol::GetAccountRateLimitsResponse;
use crewon_app_server_protocol::GetAccountResponse;
use crewon_app_server_protocol::GetAccountTokenUsageResponse;
use crewon_app_server_protocol::GetAuthStatusParams;
use crewon_app_server_protocol::GetAuthStatusResponse;
use crewon_app_server_protocol::GetConversationSummaryParams;
use crewon_app_server_protocol::GetConversationSummaryResponse;
use crewon_app_server_protocol::GitDiffToRemoteParams;
use crewon_app_server_protocol::GitDiffToRemoteResponse;
use crewon_app_server_protocol::GitInfo as ApiGitInfo;
use crewon_app_server_protocol::HookMetadata;
use crewon_app_server_protocol::HooksListParams;
use crewon_app_server_protocol::HooksListResponse;
use crewon_app_server_protocol::InitializeParams;
use crewon_app_server_protocol::InitializeResponse;
use crewon_app_server_protocol::JSONRPCErrorError;
use crewon_app_server_protocol::ListMcpServerStatusParams;
use crewon_app_server_protocol::ListMcpServerStatusResponse;
use crewon_app_server_protocol::LoginAccountParams;
use crewon_app_server_protocol::LoginAccountResponse;
use crewon_app_server_protocol::LoginApiKeyParams;
use crewon_app_server_protocol::LogoutAccountResponse;
use crewon_app_server_protocol::MarketplaceAddParams;
use crewon_app_server_protocol::MarketplaceAddResponse;
use crewon_app_server_protocol::MarketplaceInterface;
use crewon_app_server_protocol::MarketplaceRemoveParams;
use crewon_app_server_protocol::MarketplaceRemoveResponse;
use crewon_app_server_protocol::MarketplaceUpgradeErrorInfo;
use crewon_app_server_protocol::MarketplaceUpgradeParams;
use crewon_app_server_protocol::MarketplaceUpgradeResponse;
use crewon_app_server_protocol::McpResourceReadParams;
use crewon_app_server_protocol::McpResourceReadResponse;
use crewon_app_server_protocol::McpServerConfigDeleteParams;
use crewon_app_server_protocol::McpServerConfigDeleteResponse;
use crewon_app_server_protocol::McpServerConfigListParams;
use crewon_app_server_protocol::McpServerConfigListResponse;
use crewon_app_server_protocol::McpServerConfigReadParams;
use crewon_app_server_protocol::McpServerConfigReadResponse;
use crewon_app_server_protocol::McpServerConfigRecord;
use crewon_app_server_protocol::McpServerConfigSaveParams;
use crewon_app_server_protocol::McpServerConfigSaveResponse;
use crewon_app_server_protocol::McpServerConfigWriteResult;
use crewon_app_server_protocol::McpServerOauthLoginCompletedNotification;
use crewon_app_server_protocol::McpServerOauthLoginParams;
use crewon_app_server_protocol::McpServerOauthLoginResponse;
use crewon_app_server_protocol::McpServerRefreshResponse;
use crewon_app_server_protocol::McpServerStatus;
use crewon_app_server_protocol::McpServerStatusDetail;
use crewon_app_server_protocol::McpServerToolCallParams;
use crewon_app_server_protocol::McpServerToolCallResponse;
use crewon_app_server_protocol::MemoryResetResponse;
use crewon_app_server_protocol::MergeStrategy;
use crewon_app_server_protocol::MockExperimentalMethodParams;
use crewon_app_server_protocol::MockExperimentalMethodResponse;
use crewon_app_server_protocol::ModelListParams;
use crewon_app_server_protocol::ModelListResponse;
use crewon_app_server_protocol::PermissionProfileListParams;
use crewon_app_server_protocol::PermissionProfileListResponse;
use crewon_app_server_protocol::PermissionProfileSummary;
use crewon_app_server_protocol::PluginDetail;
use crewon_app_server_protocol::PluginInstallParams;
use crewon_app_server_protocol::PluginInstallResponse;
use crewon_app_server_protocol::PluginInstalledParams;
use crewon_app_server_protocol::PluginInstalledResponse;
use crewon_app_server_protocol::PluginInterface;
use crewon_app_server_protocol::PluginListMarketplaceKind;
use crewon_app_server_protocol::PluginListParams;
use crewon_app_server_protocol::PluginListResponse;
use crewon_app_server_protocol::PluginMarketplaceEntry;
use crewon_app_server_protocol::PluginReadParams;
use crewon_app_server_protocol::PluginReadResponse;
use crewon_app_server_protocol::PluginShareCheckoutParams;
use crewon_app_server_protocol::PluginShareCheckoutResponse;
use crewon_app_server_protocol::PluginShareContext;
use crewon_app_server_protocol::PluginShareDeleteParams;
use crewon_app_server_protocol::PluginShareDeleteResponse;
use crewon_app_server_protocol::PluginShareDiscoverability;
use crewon_app_server_protocol::PluginShareListItem;
use crewon_app_server_protocol::PluginShareListParams;
use crewon_app_server_protocol::PluginShareListResponse;
use crewon_app_server_protocol::PluginSharePrincipal;
use crewon_app_server_protocol::PluginSharePrincipalType;
use crewon_app_server_protocol::PluginShareSaveParams;
use crewon_app_server_protocol::PluginShareSaveResponse;
use crewon_app_server_protocol::PluginShareTarget;
use crewon_app_server_protocol::PluginShareUpdateDiscoverability;
use crewon_app_server_protocol::PluginShareUpdateTargetsParams;
use crewon_app_server_protocol::PluginShareUpdateTargetsResponse;
use crewon_app_server_protocol::PluginSkillReadParams;
use crewon_app_server_protocol::PluginSkillReadResponse;
use crewon_app_server_protocol::PluginSource;
use crewon_app_server_protocol::PluginSummary;
use crewon_app_server_protocol::PluginUninstallParams;
use crewon_app_server_protocol::PluginUninstallResponse;
use crewon_app_server_protocol::RequestId;
use crewon_app_server_protocol::ReviewDelivery as ApiReviewDelivery;
use crewon_app_server_protocol::ReviewStartParams;
use crewon_app_server_protocol::ReviewStartResponse;
use crewon_app_server_protocol::ReviewTarget as ApiReviewTarget;
use crewon_app_server_protocol::SandboxMode;
use crewon_app_server_protocol::SendAddCreditsNudgeEmailParams;
use crewon_app_server_protocol::SendAddCreditsNudgeEmailResponse;
use crewon_app_server_protocol::ServerNotification;
use crewon_app_server_protocol::ServerRequestResolvedNotification;
use crewon_app_server_protocol::SkillSummary;
use crewon_app_server_protocol::SkillsConfigWriteParams;
use crewon_app_server_protocol::SkillsConfigWriteResponse;
use crewon_app_server_protocol::SkillsCreateParams;
use crewon_app_server_protocol::SkillsCreateResponse;
use crewon_app_server_protocol::SkillsExtraRootsSetParams;
use crewon_app_server_protocol::SkillsExtraRootsSetResponse;
use crewon_app_server_protocol::SkillsListParams;
use crewon_app_server_protocol::SkillsListResponse;
use crewon_app_server_protocol::SortDirection;
use crewon_app_server_protocol::Thread;
use crewon_app_server_protocol::ThreadApproveGuardianDeniedActionParams;
use crewon_app_server_protocol::ThreadApproveGuardianDeniedActionResponse;
use crewon_app_server_protocol::ThreadArchiveParams;
use crewon_app_server_protocol::ThreadArchiveResponse;
use crewon_app_server_protocol::ThreadArchivedNotification;
use crewon_app_server_protocol::ThreadBackgroundTerminal;
use crewon_app_server_protocol::ThreadBackgroundTerminalsCleanParams;
use crewon_app_server_protocol::ThreadBackgroundTerminalsCleanResponse;
use crewon_app_server_protocol::ThreadBackgroundTerminalsListParams;
use crewon_app_server_protocol::ThreadBackgroundTerminalsListResponse;
use crewon_app_server_protocol::ThreadBackgroundTerminalsTerminateParams;
use crewon_app_server_protocol::ThreadBackgroundTerminalsTerminateResponse;
use crewon_app_server_protocol::ThreadClosedNotification;
use crewon_app_server_protocol::ThreadCompactStartParams;
use crewon_app_server_protocol::ThreadCompactStartResponse;
use crewon_app_server_protocol::ThreadDecrementElicitationParams;
use crewon_app_server_protocol::ThreadDecrementElicitationResponse;
use crewon_app_server_protocol::ThreadDeleteParams;
use crewon_app_server_protocol::ThreadDeleteResponse;
use crewon_app_server_protocol::ThreadDeletedNotification;
use crewon_app_server_protocol::ThreadForkParams;
use crewon_app_server_protocol::ThreadForkResponse;
use crewon_app_server_protocol::ThreadGoal;
use crewon_app_server_protocol::ThreadGoalClearParams;
use crewon_app_server_protocol::ThreadGoalClearResponse;
use crewon_app_server_protocol::ThreadGoalClearedNotification;
use crewon_app_server_protocol::ThreadGoalGetParams;
use crewon_app_server_protocol::ThreadGoalGetResponse;
use crewon_app_server_protocol::ThreadGoalSetParams;
use crewon_app_server_protocol::ThreadGoalSetResponse;
use crewon_app_server_protocol::ThreadGoalStatus;
use crewon_app_server_protocol::ThreadGoalUpdatedNotification;
use crewon_app_server_protocol::ThreadHistoryBuilder;
use crewon_app_server_protocol::ThreadIncrementElicitationParams;
use crewon_app_server_protocol::ThreadIncrementElicitationResponse;
use crewon_app_server_protocol::ThreadInjectItemsParams;
use crewon_app_server_protocol::ThreadInjectItemsResponse;
use crewon_app_server_protocol::ThreadItem;
use crewon_app_server_protocol::ThreadListCwdFilter;
use crewon_app_server_protocol::ThreadListParams;
use crewon_app_server_protocol::ThreadListResponse;
use crewon_app_server_protocol::ThreadLoadedListParams;
use crewon_app_server_protocol::ThreadLoadedListResponse;
use crewon_app_server_protocol::ThreadMemoryModeSetParams;
use crewon_app_server_protocol::ThreadMemoryModeSetResponse;
use crewon_app_server_protocol::ThreadMetadataGitInfoUpdateParams;
use crewon_app_server_protocol::ThreadMetadataUpdateParams;
use crewon_app_server_protocol::ThreadMetadataUpdateResponse;
use crewon_app_server_protocol::ThreadNameUpdatedNotification;
use crewon_app_server_protocol::ThreadReadParams;
use crewon_app_server_protocol::ThreadReadResponse;
use crewon_app_server_protocol::ThreadRealtimeAppendAudioParams;
use crewon_app_server_protocol::ThreadRealtimeAppendAudioResponse;
use crewon_app_server_protocol::ThreadRealtimeAppendTextParams;
use crewon_app_server_protocol::ThreadRealtimeAppendTextResponse;
use crewon_app_server_protocol::ThreadRealtimeListVoicesResponse;
use crewon_app_server_protocol::ThreadRealtimeStartParams;
use crewon_app_server_protocol::ThreadRealtimeStartResponse;
use crewon_app_server_protocol::ThreadRealtimeStartTransport;
use crewon_app_server_protocol::ThreadRealtimeStopParams;
use crewon_app_server_protocol::ThreadRealtimeStopResponse;
use crewon_app_server_protocol::ThreadResumeInitialTurnsPageParams;
use crewon_app_server_protocol::ThreadResumeParams;
use crewon_app_server_protocol::ThreadResumeResponse;
use crewon_app_server_protocol::ThreadRollbackParams;
use crewon_app_server_protocol::ThreadSearchParams;
use crewon_app_server_protocol::ThreadSearchResponse;
use crewon_app_server_protocol::ThreadSearchResult;
use crewon_app_server_protocol::ThreadSetNameParams;
use crewon_app_server_protocol::ThreadSetNameResponse;
use crewon_app_server_protocol::ThreadSettings;
use crewon_app_server_protocol::ThreadSettingsUpdateParams;
use crewon_app_server_protocol::ThreadSettingsUpdateResponse;
use crewon_app_server_protocol::ThreadShellCommandParams;
use crewon_app_server_protocol::ThreadShellCommandResponse;
use crewon_app_server_protocol::ThreadSortKey;
use crewon_app_server_protocol::ThreadSourceKind;
use crewon_app_server_protocol::ThreadStartParams;
use crewon_app_server_protocol::ThreadStartResponse;
use crewon_app_server_protocol::ThreadStartedNotification;
use crewon_app_server_protocol::ThreadStatus;
use crewon_app_server_protocol::ThreadTurnsItemsListParams;
use crewon_app_server_protocol::ThreadTurnsListParams;
use crewon_app_server_protocol::ThreadTurnsListResponse;
use crewon_app_server_protocol::ThreadUnarchiveParams;
use crewon_app_server_protocol::ThreadUnarchiveResponse;
use crewon_app_server_protocol::ThreadUnarchivedNotification;
use crewon_app_server_protocol::ThreadUnsubscribeParams;
use crewon_app_server_protocol::ThreadUnsubscribeResponse;
use crewon_app_server_protocol::ThreadUnsubscribeStatus;
use crewon_app_server_protocol::Turn;
use crewon_app_server_protocol::TurnEnvironmentParams;
use crewon_app_server_protocol::TurnError;
use crewon_app_server_protocol::TurnInterruptParams;
use crewon_app_server_protocol::TurnInterruptResponse;
use crewon_app_server_protocol::TurnItemsView;
use crewon_app_server_protocol::TurnStartParams;
use crewon_app_server_protocol::TurnStartResponse;
use crewon_app_server_protocol::TurnStatus;
use crewon_app_server_protocol::TurnSteerParams;
use crewon_app_server_protocol::TurnSteerResponse;
use crewon_app_server_protocol::UserInput as V2UserInput;
use crewon_app_server_protocol::WindowsSandboxReadiness;
use crewon_app_server_protocol::WindowsSandboxReadinessResponse;
use crewon_app_server_protocol::WindowsSandboxSetupCompletedNotification;
use crewon_app_server_protocol::WindowsSandboxSetupMode;
use crewon_app_server_protocol::WindowsSandboxSetupStartParams;
use crewon_app_server_protocol::WindowsSandboxSetupStartResponse;
use crewon_arg0::Arg0DispatchPaths;
use crewon_backend_client::AddCreditsNudgeCreditType as BackendAddCreditsNudgeCreditType;
use crewon_backend_client::Client as BackendClient;
use crewon_backend_client::TokenUsageProfile;
use crewon_chatgpt::connectors;
use crewon_chatgpt::workspace_settings;
use crewon_config::CloudConfigBundleLoadError;
use crewon_config::CloudConfigBundleLoadErrorCode;
use crewon_config::ConfigLayerStack;
use crewon_config::loader::project_trust_key;
use crewon_config::types::McpServerTransportConfig;
use crewon_core::CrewonThread;
use crewon_core::CrewonThreadSettingsOverrides;
use crewon_core::ForkSnapshot;
use crewon_core::McpManager;
use crewon_core::NewThread;
#[cfg(test)]
use crewon_core::SessionMeta;
use crewon_core::StartThreadOptions;
use crewon_core::SteerInputError;
use crewon_core::ThreadConfigSnapshot;
use crewon_core::ThreadManager;
use crewon_core::config::Config;
use crewon_core::config::ConfigOverrides;
use crewon_core::config::NetworkProxyAuditMetadata;
use crewon_core::config::edit::ConfigEdit;
use crewon_core::config::edit::ConfigEditsBuilder;
use crewon_core::connectors::AccessibleConnectorsStatus;
use crewon_core::exec::ExecCapturePolicy;
use crewon_core::exec::ExecExpiration;
use crewon_core::exec::ExecParams;
use crewon_core::exec_env::create_env;
use crewon_core::path_utils;
#[cfg(test)]
use crewon_core::read_head_for_summary;
use crewon_core::sandboxing::SandboxPermissions;
use crewon_core::windows_sandbox::WindowsSandboxLevelExt;
use crewon_core::windows_sandbox::WindowsSandboxSetupMode as CoreWindowsSandboxSetupMode;
use crewon_core::windows_sandbox::WindowsSandboxSetupRequest;
use crewon_core::windows_sandbox::sandbox_setup_is_complete;
use crewon_core_plugins::PluginInstallError as CorePluginInstallError;
use crewon_core_plugins::PluginInstallRequest;
use crewon_core_plugins::PluginReadRequest;
use crewon_core_plugins::PluginUninstallError as CorePluginUninstallError;
use crewon_core_plugins::loader::load_plugin_apps;
use crewon_core_plugins::loader::load_plugin_mcp_servers;
use crewon_core_plugins::loader::plugin_telemetry_metadata_from_root;
use crewon_core_plugins::manifest::PluginManifestInterface;
use crewon_core_plugins::marketplace::MarketplaceError;
use crewon_core_plugins::marketplace::MarketplacePluginSource;
use crewon_core_plugins::marketplace_add::MarketplaceAddError;
use crewon_core_plugins::marketplace_add::MarketplaceAddRequest;
use crewon_core_plugins::marketplace_add::add_marketplace as add_marketplace_to_codex_home;
use crewon_core_plugins::marketplace_remove::MarketplaceRemoveError;
use crewon_core_plugins::marketplace_remove::MarketplaceRemoveRequest as CoreMarketplaceRemoveRequest;
use crewon_core_plugins::marketplace_remove::remove_marketplace;
use crewon_core_plugins::remote::RemoteMarketplace;
use crewon_core_plugins::remote::RemoteMarketplaceSource;
use crewon_core_plugins::remote::RemotePluginCatalogError;
use crewon_core_plugins::remote::RemotePluginDetail as RemoteCatalogPluginDetail;
use crewon_core_plugins::remote::RemotePluginServiceConfig;
use crewon_core_plugins::remote::RemotePluginShareContext as RemoteCatalogPluginShareContext;
use crewon_core_plugins::remote::RemotePluginShareSummary as RemoteCatalogPluginShareSummary;
use crewon_core_plugins::remote::RemotePluginSummary as RemoteCatalogPluginSummary;
use crewon_exec_server::EnvironmentManager;
use crewon_exec_server::LOCAL_ENVIRONMENT_ID;
use crewon_exec_server::LOCAL_FS;
use crewon_features::FEATURES;
use crewon_features::Feature;
use crewon_features::Stage;
use crewon_feedback::CrewonFeedback;
use crewon_feedback::FeedbackAttachmentPath;
use crewon_feedback::FeedbackUploadOptions;
use crewon_git_utils::git_diff_to_remote;
use crewon_git_utils::resolve_root_git_project_for_trust;
use crewon_login::AuthManager;
use crewon_login::CLIENT_ID;
use crewon_login::CrewonAuth;
use crewon_login::ServerOptions as LoginServerOptions;
use crewon_login::ShutdownHandle;
use crewon_login::auth::login_with_chatgpt_auth_tokens;
use crewon_login::complete_device_code_login;
use crewon_login::login_with_api_key;
use crewon_login::request_device_code;
use crewon_login::run_login_server;
use crewon_mcp::McpRuntimeContext;
use crewon_mcp::McpServerStatusSnapshot;
use crewon_mcp::McpSnapshotDetail;
use crewon_mcp::collect_mcp_server_status_snapshot_with_detail;
use crewon_mcp::discover_supported_scopes;
use crewon_mcp::read_mcp_resource as read_mcp_resource_without_thread;
use crewon_mcp::resolve_oauth_scopes;
use crewon_memories_write::clear_memory_roots_contents;
use crewon_model_provider::create_model_provider;
use crewon_models_manager::collaboration_mode_presets::builtin_collaboration_mode_presets;
use crewon_protocol::ThreadId;
use crewon_protocol::config_types::CollaborationMode;
use crewon_protocol::config_types::ForcedLoginMethod;
use crewon_protocol::config_types::Personality;
use crewon_protocol::config_types::ReasoningSummary;
use crewon_protocol::config_types::TrustLevel;
use crewon_protocol::config_types::WindowsSandboxLevel;
use crewon_protocol::dynamic_tools::DynamicToolSpec as CoreDynamicToolSpec;
use crewon_protocol::error::CodexErr;
use crewon_protocol::error::Result as CrewonResult;
#[cfg(test)]
use crewon_protocol::items::TurnItem;
use crewon_protocol::models::BUILT_IN_PERMISSION_PROFILE_DANGER_FULL_ACCESS;
use crewon_protocol::models::BUILT_IN_PERMISSION_PROFILE_READ_ONLY;
use crewon_protocol::models::BUILT_IN_PERMISSION_PROFILE_WORKSPACE;
use crewon_protocol::models::ResponseItem;
use crewon_protocol::openai_models::ReasoningEffort;
#[cfg(test)]
use crewon_protocol::permissions::FileSystemSandboxPolicy;
use crewon_protocol::protocol::AgentStatus;
use crewon_protocol::protocol::ConversationAudioParams;
use crewon_protocol::protocol::ConversationStartParams;
use crewon_protocol::protocol::ConversationStartTransport;
use crewon_protocol::protocol::ConversationTextParams;
use crewon_protocol::protocol::EventMsg;
#[cfg(test)]
use crewon_protocol::protocol::GitInfo as CoreGitInfo;
use crewon_protocol::protocol::InitialHistory;
use crewon_protocol::protocol::McpAuthStatus as CoreMcpAuthStatus;
use crewon_protocol::protocol::Op;
use crewon_protocol::protocol::RateLimitSnapshot as CoreRateLimitSnapshot;
use crewon_protocol::protocol::RealtimeVoicesList;
use crewon_protocol::protocol::ResumedHistory;
use crewon_protocol::protocol::ReviewDelivery as CoreReviewDelivery;
use crewon_protocol::protocol::ReviewRequest;
use crewon_protocol::protocol::ReviewTarget as CoreReviewTarget;
use crewon_protocol::protocol::RolloutItem;
use crewon_protocol::protocol::SessionConfiguredEvent;
#[cfg(test)]
use crewon_protocol::protocol::SessionMetaLine;
use crewon_protocol::protocol::TurnEnvironmentSelection;
use crewon_protocol::protocol::TurnEnvironmentSelections;
use crewon_protocol::protocol::USER_MESSAGE_BEGIN;
use crewon_protocol::protocol::W3cTraceContext;
use crewon_protocol::user_input::MAX_USER_INPUT_TEXT_CHARS;
use crewon_protocol::user_input::UserInput as CoreInputItem;
use crewon_rmcp_client::perform_oauth_login_return_url;
use crewon_rollout::is_persisted_rollout_item;
use crewon_rollout::state_db::StateDbHandle;
use crewon_rollout::state_db::reconcile_rollout;
use crewon_state::ThreadMetadata;
use crewon_state::log_db::LogDbLayer;
use crewon_thread_store::ArchiveThreadParams as StoreArchiveThreadParams;
use crewon_thread_store::DeleteThreadParams as StoreDeleteThreadParams;
use crewon_thread_store::GitInfoPatch as StoreGitInfoPatch;
use crewon_thread_store::ListThreadsParams as StoreListThreadsParams;
use crewon_thread_store::LocalThreadStore;
use crewon_thread_store::ReadThreadByRolloutPathParams as StoreReadThreadByRolloutPathParams;
use crewon_thread_store::ReadThreadParams as StoreReadThreadParams;
use crewon_thread_store::SearchThreadsParams as StoreSearchThreadsParams;
use crewon_thread_store::SortDirection as StoreSortDirection;
use crewon_thread_store::StoredThread;
use crewon_thread_store::ThreadMetadataPatch as StoreThreadMetadataPatch;
use crewon_thread_store::ThreadSortKey as StoreThreadSortKey;
use crewon_thread_store::ThreadStore;
use crewon_thread_store::ThreadStoreError;
use crewon_utils_absolute_path::AbsolutePathBuf;
use crewon_utils_pty::DEFAULT_OUTPUT_BYTES_CAP;
use std::collections::BTreeMap;
use std::collections::HashMap;
use std::collections::HashSet;
use std::io::Error as IoError;
use std::path::Path;
use std::path::PathBuf;
use std::result::Result;
use std::sync::Arc;
use std::time::Duration;
use std::time::Instant;
use tokio::sync::Mutex;
use tokio::sync::Semaphore;
use tokio::sync::SemaphorePermit;
use tokio::sync::broadcast;
use tokio::sync::oneshot;
use tokio::sync::watch;
use tokio_util::sync::CancellationToken;
use tokio_util::sync::DropGuard;
use tokio_util::task::TaskTracker;
use toml::Value as TomlValue;
use tracing::Instrument;
use tracing::error;
use tracing::info;
use tracing::warn;
use uuid::Uuid;

#[cfg(test)]
use crewon_app_server_protocol::ServerRequest;

mod account_processor;
mod apps_processor;
mod catalog_processor;
mod command_exec_processor;
mod config_processor;
mod crewon_domain_processor;
mod environment_processor;
mod external_agent_config_processor;
mod external_agent_session_import;
mod feedback_doctor_report;
mod feedback_processor;
mod fs_processor;
mod git_processor;
mod initialize_processor;
mod knowledge_processor;
mod marketplace_processor;
mod mcp_config_processor;
mod mcp_processor;
mod plugins;
mod process_exec_processor;
mod remote_control_processor;
mod search;
mod thread_processor;
mod token_usage_replay;
mod turn_processor;
mod windows_sandbox_processor;

pub(crate) use account_processor::AccountRequestProcessor;
pub(crate) use apps_processor::AppsRequestProcessor;
pub(crate) use catalog_processor::CatalogRequestProcessor;
pub(crate) use command_exec_processor::CommandExecRequestProcessor;
pub(crate) use config_processor::ConfigRequestProcessor;
pub(crate) use crewon_domain_processor::CrewonDomainRequestProcessor;
pub(crate) use crewon_domain_processor::OfficeAutoDispatchIntentDispatched;
pub(crate) use crewon_domain_processor::OfficeVerificationDispatchStarted;
pub(crate) use crewon_domain_processor::office_run_updated_notification;
pub(crate) use crewon_domain_processor::sync_automation_runs_for_thread_turn;
pub(crate) use crewon_domain_processor::sync_office_run_updates_for_thread_turn;
pub(crate) use environment_processor::EnvironmentRequestProcessor;
pub(crate) use external_agent_config_processor::ExternalAgentConfigRequestProcessor;
pub(crate) use feedback_processor::FeedbackRequestProcessor;
pub(crate) use fs_processor::FsRequestProcessor;
pub(crate) use git_processor::GitRequestProcessor;
pub(crate) use initialize_processor::InitializeRequestProcessor;
pub(crate) use knowledge_processor::KnowledgeRequestProcessor;
pub(crate) use marketplace_processor::MarketplaceRequestProcessor;
pub(crate) use mcp_config_processor::McpConfigRequestProcessor;
pub(crate) use mcp_processor::McpRequestProcessor;
pub(crate) use plugins::PluginRequestProcessor;
pub(crate) use process_exec_processor::ProcessExecRequestProcessor;
pub(crate) use remote_control_processor::RemoteControlRequestProcessor;
pub(crate) use search::SearchRequestProcessor;
pub(crate) use thread_goal_processor::ThreadGoalRequestProcessor;
pub(crate) use thread_processor::OfficeMemberRuntimeThreadStart;
pub(crate) use thread_processor::ThreadRequestProcessor;
pub(crate) use turn_processor::TurnRequestProcessor;
pub(crate) use windows_sandbox_processor::WindowsSandboxRequestProcessor;

use crate::error_code::internal_error;
use crate::error_code::invalid_request;
use crate::filters::compute_source_filters;
use crate::filters::source_kind_matches;
use crate::thread_state::ConnectionCapabilities;
use crate::thread_state::ThreadListenerCommand;
use crate::thread_state::ThreadState;
use crate::thread_state::ThreadStateManager;
use token_usage_replay::latest_token_usage_turn_id_from_rollout_items;
use token_usage_replay::send_thread_token_usage_update_to_connection;

fn resolve_request_cwd(cwd: Option<PathBuf>) -> Result<Option<AbsolutePathBuf>, JSONRPCErrorError> {
    cwd.map(|cwd| {
        AbsolutePathBuf::relative_to_current_dir(path_utils::normalize_for_native_workdir(cwd))
            .map_err(|err| invalid_request(format!("invalid cwd: {err}")))
    })
    .transpose()
}

fn resolve_runtime_workspace_roots(workspace_roots: Vec<AbsolutePathBuf>) -> Vec<AbsolutePathBuf> {
    let mut resolved_roots = Vec::new();
    for root in workspace_roots {
        if !resolved_roots.iter().any(|existing| existing == &root) {
            resolved_roots.push(root);
        }
    }
    resolved_roots
}

mod config_errors;
mod office_auto_dispatch;
mod request_errors;
mod thread_delete;
mod thread_goal_processor;
mod thread_lifecycle;
mod thread_resume_redaction;
mod thread_summary;

use self::config_errors::*;
use self::office_auto_dispatch::office_terminal_turn_from_event;
use self::request_errors::*;
use self::thread_goal_processor::api_thread_goal_from_state;
use self::thread_lifecycle::*;
use self::thread_resume_redaction::*;
use self::thread_summary::*;

pub(crate) use self::office_auto_dispatch::OfficeAutoDispatchContext;
pub(crate) use self::office_auto_dispatch::OfficeAutoDispatchStarted;
pub(crate) use self::thread_lifecycle::populate_thread_turns_from_history;
pub(crate) use self::thread_processor::thread_from_stored_thread;
#[cfg(test)]
pub(crate) use self::thread_summary::read_summary_from_rollout;
#[cfg(test)]
pub(crate) use self::thread_summary::summary_to_thread;
pub(crate) use self::thread_summary::thread_settings_from_config_snapshot;
pub(crate) use self::thread_summary::thread_settings_from_core_snapshot;

pub(crate) fn build_api_turns_from_rollout_items(items: &[RolloutItem]) -> Vec<Turn> {
    let mut builder = ThreadHistoryBuilder::new();
    for item in items {
        if is_persisted_rollout_item(item) {
            builder.handle_rollout_item(item);
        }
    }
    builder.finish()
}
