// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfigRecord } from "./McpServerConfigRecord";

export type McpServerConfigReadResponse = { record: McpServerConfigRecord | null, };
