[package]
name = "crewon-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crewon-core = { workspace = true }
crewon-model-provider-info = { workspace = true }
crewon-protocol = { workspace = true }
crewon-utils-absolute-path = { workspace = true }

[dev-dependencies]
crewon-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
name = "crewon_utils_sandbox_summary"
doctest = false
