[package]
name = "crewon-utils-oss"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crewon-core = { workspace = true }
crewon-lmstudio = { workspace = true }
crewon-model-provider-info = { workspace = true }
crewon-ollama = { workspace = true }

[lib]
name = "crewon_utils_oss"
doctest = false
