[package]
name = "crewon-arg0"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "crewon_arg0"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
crewon-apply-patch = { workspace = true }
crewon-exec-server = { workspace = true }
crewon-install-context = { workspace = true }
crewon-linux-sandbox = { workspace = true }
crewon-sandboxing = { workspace = true }
crewon-shell-escalation = { workspace = true }
crewon-utils-absolute-path = { workspace = true }
crewon-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
