[package]
edition.workspace = true
license.workspace = true
name = "crewon-device"
version.workspace = true

[lib]
name = "crewon_device"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
crewon-device-protocol = { workspace = true }
ed25519-dalek = { workspace = true, features = ["pem"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
crewon-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
