[package]
edition.workspace = true
license.workspace = true
name = "crewon-memories-read"
version.workspace = true

[lib]
name = "crewon_memories_read"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
crewon-protocol = { workspace = true }
crewon-shell-command = { workspace = true }
crewon-utils-absolute-path = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
