[package]
edition.workspace = true
license.workspace = true
name = "crewon-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
crewon-protocol = { workspace = true }
crewon-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
name = "crewon_utils_output_truncation"
