[package]
edition.workspace = true
license.workspace = true
name = "crewon-core-api"
version.workspace = true

[lib]
doctest = false
name = "crewon_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
crewon-app-server-protocol = { workspace = true }
crewon-arg0 = { workspace = true }
crewon-analytics = { workspace = true }
crewon-config = { workspace = true }
crewon-core = { workspace = true }
crewon-extension-api = { workspace = true }
crewon-exec-server = { workspace = true }
crewon-features = { workspace = true }
crewon-login = { workspace = true }
crewon-model-provider-info = { workspace = true }
crewon-models-manager = { workspace = true }
crewon-protocol = { workspace = true }
crewon-utils-absolute-path = { workspace = true }
