[package]
name = "crewon-utils-cargo-bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
assert_cmd = { workspace = true }
runfiles = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "crewon_utils_cargo_bin"
test = false
doctest = false
