[package]
name = "crewon-utils-options"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true, features = ["derive", "wrap_help"] }
serde = { workspace = true }
toml = { workspace = true }

[lib]
name = "crewon_utils_options"
doctest = false
