[package]
name = "crewon-file-system"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
crewon-protocol = { workspace = true }
crewon-utils-absolute-path = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lib]
name = "crewon_file_system"
test = false
doctest = false
